[package]
name = "islam"
version = "2.0.0"
authors = ["azzamsa <me@azzamsa.com>"]
categories = ["date-and-time", "science"]
edition = "2021"
keywords = ["salah", "pray", "islam", "hijri"]
license = "GPL-3.0-only"
readme = "README.md"
repository = "https://github.com/azzamsa/islam"
description = "Islamic library for Rust"

[dependencies]
chrono = "0.4.19"
thiserror = "1.0"

[package.metadata.release]
tag-message = "For details, see the CHANGELOG.md"
pre-release-commit-message = "v{{version}}"
pre-release-hook = ["just", "_prepare-release", "{{version}}"]
