[package]
name = "islam"
description = "Islamic library for Rust"
version = "0.1.1"
authors = ["azzamsa <me@azzamsa.com>"]
edition = "2018"
keywords = ["salah", "pray", "islam", "hijri"]
categories = ["date-and-time", "command-line-utilities"]
readme = "README.md"
license = "GPL-3.0-only"
repository = "https://git.sr.ht/~azzamsa/islam"

[dependencies]
chrono = "0.4.19"
thiserror = "1.0.24"
